---
title: "Final Report"
author: "Nicholas Treloar, Jiamin Zou, Yalei Zhao"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Assessing Predictive Performance and Gene Selection Consistency in Gene Expression Models

Introduction

-   Introduction of Dataset

-   Introduction of question of interest

-   Introduction of Methods, Packages, and approach(es) taken

LASSO

Support Vector Machine

Random Forest

Neural Network

Results

The report is clearly written and sufficiently introduces the dataset of choice, the question of interest, the approach taken, and the results. Furthermore the following requirements should also be satisfied if possible (otherwise a penalty may be applied): ˆ R Markdown should be used to write the report for the final project. ˆ The report should have a meaningful title, an author list, an abstract/summary, an introduc- tion section, a method section, a result section, a conclusion section, references, and has no more than 5 pages with everything included. ˆ The contributions from each of the group member should be clearly stated (although all the students in a group will receive equal points for the final group project). ˆ A public GitHub repository should be used for the group members to collaborate on the final project, with a link to it provided in the report. ˆ Graphics (ideally with ggplot2) should be used to present the results
